### ISSUE TITLE
Hamburger Menu not aligned

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/dwatch#10]
Ubuntu 16
![dwatch_001](https://cloud.githubusercontent.com/assets/546815/15480922/435142de-2128-11e6-810a-7a51ffc2c99a.jpg)

**Comment by uweschaefer** [comment]
furthermore spinner on the right does not stop spinning...

**Comment by otbe** [comment]
Wrong alignment should be fixed in ```v1.0.0-alpha.5```.

Endless spinning spinner indicates a long-taking (never ending) request. It seems that you have one container, but no image. Thats awkward. Maybe the images request fails for some reason. Did you get a notification? You definitely need some first level support :D

**Comment by uweschaefer** [comment]
alignment fix tested. thx
