### ISSUE TITLE
Button to remove all stopped containers

### ISSUE THREAD

**Issue by mweststrate** [Mercateo/dwatch#19]
Hey @otbe / @donaldpipowitch !

Just started with docker and gave DWatch a spin. Really useful :) Minor feature request, with all the expirimenting I often create unnecessary containers. Would be nice if there was a button to clean up all stopped containers.

Thanks!

**Comment by otbe** [comment]
@mweststrate valid request 👍 
Will be added in 1.0.0-alpha.6 :)

**Comment by otbe** [comment]
1.0.0-alpha.6 released

**Comment by uweschaefer** [comment]
nice, but afterwards, screen should reload to see the containers gone...

**Comment by otbe** [comment]
@uweschaefer this should happen automatically, because DWatch listens to docker events (via Docker Remote API). 
Do you get redirected to containers list page (pic2) if you remove a stopped container via detail page (pic1)?
<img width="1428" alt="bildschirmfoto 2016-07-12 um 21 01 53" src="https://cloud.githubusercontent.com/assets/3391052/16779803/14e2eb78-4874-11e6-8be9-e00a8655f82c.png">
<img width="1437" alt="bildschirmfoto 2016-07-12 um 21 02 05" src="https://cloud.githubusercontent.com/assets/3391052/16779804/16432c62-4874-11e6-9e7c-cd6740883fca.png">

**Comment by mweststrate** [comment]
@otbe thanks for the quick implementation! Gonna test drive it soon

**Comment by mweststrate** [comment]
Tested, works, thanks! If I remember correctly the containers where removed immediately. Issue can be close as far as I am concerned. Feel free to leave it open to investigate @uweschaefer's comment.
